"""phase 2 domain schema

Revision ID: 80d2893ee48c
Revises: 
Create Date: 2026-09-29 13:54:50.144455
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80d2893ee48c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='ck_academic_year_dates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_academic_years_name')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name', name='uq_departments_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'faculty', 'student')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('credits', sa.Integer(), server_default='3', nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credits > 0', name='ck_courses_credits_positive'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id', 'department_id', name='uq_courses_id_department')
    )
    op.create_index(op.f('ix_courses_department_id'), 'courses', ['department_id'], unique=False)
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_faculty_department_active', 'faculty', ['department_id', 'is_active'], unique=False)
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('audience', sa.String(length=20), server_default='all', nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("audience IN ('all', 'admin', 'faculty', 'student')", name='ck_notices_audience'),
    sa.CheckConstraint('expires_at IS NULL OR published_at IS NULL OR expires_at > published_at', name='ck_notices_dates'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notices_published_audience', 'notices', ['is_published', 'audience', 'published_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=40), server_default='general', nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='ck_semesters_dates'),
    sa.CheckConstraint('number > 0', name='ck_semesters_number_positive'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'name', name='uq_semesters_year_name'),
    sa.UniqueConstraint('academic_year_id', 'number', name='uq_semesters_year_number'),
    sa.UniqueConstraint('id', 'academic_year_id', name='uq_semesters_id_year')
    )
    op.create_index(op.f('ix_semesters_academic_year_id'), 'semesters', ['academic_year_id'], unique=False)
    op.create_table('course_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=20), server_default='A', nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('room', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity IS NULL OR capacity > 0', name='ck_offering_capacity_positive'),
    sa.CheckConstraint('length(trim(section)) > 0', name='ck_offering_section_not_blank'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'semester_id', 'section', name='uq_offering_course_semester_section'),
    sa.UniqueConstraint('faculty_id', 'id', name='uq_offerings_faculty_id'),
    sa.UniqueConstraint('id', 'semester_id', name='uq_offerings_id_semester')
    )
    op.create_index(op.f('ix_course_offerings_course_id'), 'course_offerings', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_offerings_faculty_id'), 'course_offerings', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_course_offerings_semester_id'), 'course_offerings', ['semester_id'], unique=False)
    op.create_index('ix_offerings_faculty_semester', 'course_offerings', ['faculty_id', 'semester_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('exam_type', sa.String(length=40), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'scheduled', 'completed', 'cancelled')", name='ck_exams_status'),
    sa.CheckConstraint('end_date >= start_date', name='ck_exams_dates'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'semester_id', name='uq_exams_id_semester')
    )
    op.create_index(op.f('ix_exams_semester_id'), 'exams', ['semester_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_number', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_students_department_semester', 'students', ['department_id', 'semester_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_marks', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('attachment_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'closed')", name='ck_assignments_status'),
    sa.CheckConstraint('max_marks > 0', name='ck_assignments_max_marks_positive'),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faculty_id', 'course_offering_id'], ['course_offerings.faculty_id', 'course_offerings.id'], name='fk_assignments_faculty_offering', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'course_offering_id', name='uq_assignments_id_offering')
    )
    op.create_index(op.f('ix_assignments_course_offering_id'), 'assignments', ['course_offering_id'], unique=False)
    op.create_index(op.f('ix_assignments_faculty_id'), 'assignments', ['faculty_id'], unique=False)
    op.create_index('ix_assignments_offering_due', 'assignments', ['course_offering_id', 'due_date'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time IS NULL OR start_time IS NULL OR end_time > start_time', name='ck_attendance_session_times'),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faculty_id', 'course_offering_id'], ['course_offerings.faculty_id', 'course_offerings.id'], name='fk_attendance_session_faculty_offering', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_offering_id', 'session_date', 'start_time', name='uq_attendance_session_period'),
    sa.UniqueConstraint('id', 'course_offering_id', name='uq_attendance_sessions_id_offering')
    )
    op.create_index(op.f('ix_attendance_sessions_course_offering_id'), 'attendance_sessions', ['course_offering_id'], unique=False)
    op.create_index('ix_attendance_sessions_date', 'attendance_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_faculty_id'), 'attendance_sessions', ['faculty_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'dropped', 'withdrawn')", name='ck_enrollments_status'),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_offering_id', name='uq_enrollments_student_offering')
    )
    op.create_index(op.f('ix_enrollments_course_offering_id'), 'enrollments', ['course_offering_id'], unique=False)
    op.create_index('ix_enrollments_offering_status', 'enrollments', ['course_offering_id', 'status'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('exam_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_exam_schedules_times'),
    sa.ForeignKeyConstraint(['course_offering_id', 'semester_id'], ['course_offerings.id', 'course_offerings.semester_id'], name='fk_exam_schedules_offering_semester', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exam_id', 'semester_id'], ['exams.id', 'exams.semester_id'], name='fk_exam_schedules_exam_semester', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'course_offering_id', name='uq_exam_schedules_exam_offering'),
    sa.UniqueConstraint('id', 'course_offering_id', name='uq_exam_schedules_id_offering')
    )
    op.create_index('ix_exam_schedules_date', 'exam_schedules', ['exam_date'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_session_id', sa.Integer(), nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('present', 'absent', 'late', 'excused')", name='ck_attendance_records_status'),
    sa.ForeignKeyConstraint(['attendance_session_id', 'course_offering_id'], ['attendance_sessions.id', 'attendance_sessions.course_offering_id'], name='fk_attendance_records_session_offering', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id', 'course_offering_id'], ['enrollments.student_id', 'enrollments.course_offering_id'], name='fk_attendance_records_enrollment', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_session_id', 'student_id', name='uq_attendance_record_session_student')
    )
    op.create_index('ix_attendance_records_student_status', 'attendance_records', ['student_id', 'status'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('exam_schedule_id', sa.Integer(), nullable=True),
    sa.Column('assessment_name', sa.String(length=120), nullable=False),
    sa.Column('marks', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_marks', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=True),
    sa.Column('grade_point', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published')", name='ck_results_status'),
    sa.CheckConstraint('grade_point >= 0 AND grade_point <= 10', name='ck_results_grade_point_range'),
    sa.CheckConstraint('marks >= 0 AND max_marks > 0 AND marks <= max_marks', name='ck_results_marks_range'),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exam_schedule_id', 'course_offering_id'], ['exam_schedules.id', 'exam_schedules.course_offering_id'], name='fk_results_exam_schedule_offering', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id', 'course_offering_id'], ['enrollments.student_id', 'enrollments.course_offering_id'], name='fk_results_enrollment', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_offering_id', 'assessment_name', name='uq_results_student_offering_assessment')
    )
    op.create_index(op.f('ix_results_course_offering_id'), 'results', ['course_offering_id'], unique=False)
    op.create_index('ix_results_offering_status', 'results', ['course_offering_id', 'status'], unique=False)
    op.create_index(op.f('ix_results_student_id'), 'results', ['student_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('marks', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'graded', 'returned')", name='ck_submissions_status'),
    sa.CheckConstraint('marks IS NULL OR marks >= 0', name='ck_submissions_marks_nonnegative'),
    sa.ForeignKeyConstraint(['assignment_id', 'course_offering_id'], ['assignments.id', 'assignments.course_offering_id'], name='fk_submissions_assignment_offering', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id', 'course_offering_id'], ['enrollments.student_id', 'enrollments.course_offering_id'], name='fk_submissions_enrollment', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'student_id', name='uq_submissions_assignment_student')
    )
    op.create_index('ix_submissions_student_status', 'submissions', ['student_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submissions_student_status', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_results_student_id'), table_name='results')
    op.drop_index('ix_results_offering_status', table_name='results')
    op.drop_index(op.f('ix_results_course_offering_id'), table_name='results')
    op.drop_table('results')
    op.drop_index('ix_attendance_records_student_status', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('ix_exam_schedules_date', table_name='exam_schedules')
    op.drop_table('exam_schedules')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index('ix_enrollments_offering_status', table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_offering_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_attendance_sessions_faculty_id'), table_name='attendance_sessions')
    op.drop_index('ix_attendance_sessions_date', table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_course_offering_id'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index('ix_assignments_offering_due', table_name='assignments')
    op.drop_index(op.f('ix_assignments_faculty_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_course_offering_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_students_department_semester', table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_exams_semester_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index('ix_offerings_faculty_semester', table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_semester_id'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_faculty_id'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_course_id'), table_name='course_offerings')
    op.drop_table('course_offerings')
    op.drop_index(op.f('ix_semesters_academic_year_id'), table_name='semesters')
    op.drop_table('semesters')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_notices_published_audience', table_name='notices')
    op.drop_table('notices')
    op.drop_index('ix_faculty_department_active', table_name='faculty')
    op.drop_table('faculty')
    op.drop_index(op.f('ix_courses_department_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_table('users')
    op.drop_table('departments')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
