"""phase 3 lifecycle and registration

Revision ID: f54c14450324
Revises: 80d2893ee48c
Create Date: 2026-09-29 14:52:52.185853
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f54c14450324'
down_revision: Union[str, None] = '80d2893ee48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('intended_program', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='submitted', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('submitted', 'under_review', 'approved', 'rejected', 'withdrawn')", name='ck_admission_applications_status'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index('ix_admission_applications_department_year', 'admission_applications', ['department_id', 'academic_year_id'], unique=False)
    op.create_index(op.f('ix_admission_applications_email'), 'admission_applications', ['email'], unique=False)
    op.create_index('ix_admission_applications_status_submitted', 'admission_applications', ['status', 'submitted_at'], unique=False)
    op.create_table('class_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 1 AND 7', name='ck_class_schedule_weekday'),
    sa.CheckConstraint('end_time > start_time', name='ck_class_schedule_times'),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_schedules_course_offering_id'), 'class_schedules', ['course_offering_id'], unique=False)
    op.create_index('ix_class_schedules_day_time', 'class_schedules', ['day_of_week', 'start_time', 'end_time'], unique=False)
    op.add_column('course_offerings', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_offerings', 'is_active')
    op.drop_index('ix_class_schedules_day_time', table_name='class_schedules')
    op.drop_index(op.f('ix_class_schedules_course_offering_id'), table_name='class_schedules')
    op.drop_table('class_schedules')
    op.drop_index('ix_admission_applications_status_submitted', table_name='admission_applications')
    op.drop_index(op.f('ix_admission_applications_email'), table_name='admission_applications')
    op.drop_index('ix_admission_applications_department_year', table_name='admission_applications')
    op.drop_table('admission_applications')
    # ### end Alembic commands ###
